name:                snake
version:             0.1.0.0
github:              "tuesta/snake"
license:             BSD3
author:              "tuesta"
maintainer:          "tuesta@protonmail.com"
copyright:           "2020 tuesta"

extra-source-files:
- README.md
- ChangeLog.md

description:         snake-game

dependencies:
- base >= 4.7 && < 5
- random
- gloss

library:
  source-dirs: src

executables:
  snake:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -fwarn-unused-binds
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snake

tests:
  snake-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snake
